#' Predict cluster assignment for new variants using the Pareto Staircase Model
#'
#' Classifies new variants into risk tiers based on the Pareto Staircase
#' model generated by \code{cluster_score()}.  Comparison is performed in
#' raw annotation score space (no transformation or scaling applied), consistent
#' with the Pareto anchor extraction in \code{cluster_score()}.
#'
#' @param model The prediction model object.  Accepts either the full output
#'   from \code{cluster_score()} (containing \code{$prediction.model}) or the
#'   \code{prediction.model} list directly.
#' @param new.scores A data frame or matrix of raw annotation scores for new
#'   variants.  Must have the same columns as the training scores.
#' @return An integer vector of tier assignments (1 = lowest risk).
#' @export
predict_vacant_cluster <- function(model, new.scores) {

  # ---- Resolve model object ----
  if (!is.null(model$prediction.model) &&
      identical(model$prediction.model$type, "layered_pareto")) {
    pm <- model$prediction.model
  } else if (!is.null(model$type) &&
             identical(model$type, "layered_pareto")) {
    pm <- model
  } else {
    stop("Invalid model object. Expected output from cluster_score().")
  }

  if (is.vector(new.scores)) {
    new.scores <- matrix(new.scores, nrow = 1)
  } else {
    new.scores <- as.matrix(new.scores)
  }

  anchors.list <- pm$anchors.list
  K <- pm$K

  # Column validation using the first available non-null anchor set
  ref.cols <- NULL
  if (K > 1L) {
    for (k in 2:K) {
      if (!is.null(anchors.list[[k]])) {
        ref.cols <- colnames(anchors.list[[k]])
        break
      }
    }
  }

  if (!is.null(ref.cols) && !is.null(colnames(new.scores))) {
    missing.cols <- setdiff(ref.cols, colnames(new.scores))
    if (length(missing.cols) > 0L) {
      stop(paste("Missing score columns in new.scores:",
                 paste(missing.cols, collapse = ", ")))
    }
    new.scores <- new.scores[, ref.cols, drop = FALSE]
  }

  # ---- Pareto prediction (raw score space, no transform/scale) ----
  # Anchors are stored in raw annotation score space by cluster_score().
  # Comparison uses Pareto dominance: a variant is assigned to the highest
  # tier k such that it dominates at least one anchor in tier k's frontier.
  n.samples   <- nrow(new.scores)
  predictions <- rep(1L, n.samples)

  if (K > 1L) {
    for (i in seq_len(n.samples)) {
      pt <- new.scores[i, ]

      for (k in K:2) {
        anchors.k <- anchors.list[[k]]
        if (!is.null(anchors.k) && nrow(anchors.k) > 0L) {
          for (a.idx in seq_len(nrow(anchors.k))) {
            if (all(pt >= anchors.k[a.idx, ])) {
              predictions[i] <- k
              break
            }
          }
          if (predictions[i] == k) break
        }
      }
    }
  }

  return(predictions)
}
